version: "3.9"

services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./src:/usr/share/nginx/html:ro
    networks:
      - dokploy_net
    labels:
      - traefik.enable=true
      - traefik.docker.network=dokploy_dokploy_net
      - traefik.http.routers.demo.rule=Host(`demo.nolowcodes.com`)
      - traefik.http.routers.demo.entrypoints=web
      - traefik.http.services.demo.loadbalancer.server.port=80

networks:
  dokploy_net:
    external: true
